name: my_rpg_test

on:
  push:
    branches: [ master ]

jobs:
  unit_tests:
    name: unit_tests
    container: epitechcontent/epitest-docker
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      continue-on-error: true

    - name: make
      run: make
      continue-on-error: true

    - name: unitest
      run: make tests_run
      continue-on-error: true